apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quota-batman
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://<твой-репо>.git
    targetRevision: main
    path: quota-batman
  destination:
    server: https://kubernetes.default.svc
    namespace: batman
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
